name: local-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - faiss-cpu
  - numpy<2.0  # <--- Fix FAISS compatibility issue
  - pip:
      - langchain
      - langchain-community
      - langchain-huggingface
      - langchain-unstructured
      - llama-cpp-python==0.2.24
      - sentence-transformers
      - unstructured[local-inference,pdf,ppt,image,docx]
      - python-magic
      - pypandoc
      - beautifulsoup4
      - torch